name: drainit_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  google_fonts: ^2.3.1
  google_maps_flutter: ^2.1.1
  location: 4.3.0
  lottie: ^1.2.2
  persistent_bottom_nav_bar: 4.0.2
  google_nav_bar: 5.0.5
  line_icons: 2.0.1
  flutter_svg: ^1.0.3
  image_picker: ^0.8.4+10
  image_cropper: ^1.5.0
  implicitly_animated_reorderable_list: ^0.4.2
  flare_splash_screen: ^4.0.0
  material_floating_search_bar: ^0.3.6
  flutter_screenutil: ^5.3.1
  get_storage: 2.0.3
  cached_network_image: ^3.1.0
  flutter_polyline_points: 1.0.0
  geocoding: ^2.0.1
  lint: ^1.7.2
  timelines: 0.1.0
  timeline_tile: 2.0.0
  badges: 2.0.2
  dropdown_button2: ^1.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  lints: 1.0.1
  integration_test: 
    sdk: flutter
  flutter_test: 
    sdk: flutter

flutter: 
  fonts: 
    - family: Klasik
      fonts: 
        - asset: assets/fonts/Klasik-Regular.otf
  assets: 
    - assets/lottie/
    - assets/svg/
    - assets/image/
  uses-material-design: true

