name: drainit_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.2
  google_fonts: ^2.3.1
  google_maps_flutter: ^2.1.1
  location:
    git:
      url: https://github.com/TabooSun/flutterlocation.git
      path: packages/location
      ref: flutter-3-compatibility
  flutter_native_splash: ^2.1.1
  persistent_bottom_nav_bar: 4.0.2
  flutter_svg: ^1.0.3
  image_picker: ^0.8.4+10
  image_cropper: ^2.0.2
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  flutter_screenutil: ^5.5.2
  get_storage: 2.0.3
  cached_network_image: ^3.1.0
  flutter_polyline_points: 1.0.0
  geocoding: ^2.0.1
  lint: ^1.7.2
  photo_view: 0.13.0
  onesignal_flutter: 3.3.0
  auto_size_text: 3.0.0
  file_picker: 4.5.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  integration_test: 
    sdk: flutter

flutter:
  assets: 
    - assets/lottie/
    - assets/svg/
    - assets/image/
  uses-material-design: true

flutter_native_splash: 
  background_image: assets/image/splash_screen.png
  fullscreen: false

