name: drainit_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.2
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.1
  flutter_native_splash: 2.1.1
  persistent_bottom_nav_bar: 4.0.2
  flutter_svg: ^1.0.3
  image_picker: ^0.8.4+10
  image_cropper: ^2.0.2
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  flutter_screenutil: ^5.5.2
  firebase_messaging: 12.0.1
  firebase_core: ^1.19.1
  get_storage: 2.0.3
  cached_network_image: ^3.2.1
  flutter_polyline_points: 1.0.0
  geocoding: ^2.0.1
  lint: ^1.7.2
  maps_launcher: ^2.0.1
  photo_view: ^0.14.0
  auto_size_text: 3.0.0
  file_picker: ^4.6.1
  lottie: 1.3.0
  visibility_detector: 0.3.3
  shimmer: 2.0.0
  location: 4.4.0
  date_time_picker: 2.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  integration_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/svg/
    - assets/image/
  fonts: 
    - family: Raleway
      fonts: 
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
        - asset: assets/fonts/raleway/Raleway-Light.ttf
        - asset: assets/fonts/raleway/Raleway-ExtraBold.ttf
    - family: Poppins
      fonts: 
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/poppins/Poppins-Black.ttf
  uses-material-design: true

flutter_native_splash:
  background_image: assets/image/imageSplash.png

  web: false

