name: drainit_petugas
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.1.0
  dcdg: ^4.0.1
  d_chart: ^0.0.4
  get: ^4.6.5
  file_picker: ^4.5.1
  flutter_screenutil: ^5.4.0+1
  firebase_messaging: 12.0.1
  firebase_core: ^1.19.1
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.1+1
  get_storage: 2.0.3
  geocoding: ^2.0.1
  google_maps_flutter: ^2.1.9
  photo_view: ^0.14.0
  readmore: ^2.2.0
  flutter_native_splash: ^2.2.5
  shimmer: 2.0.0
  image_picker: 0.8.5+3
  image_cropper: 2.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/png/
    - assets/svg/
  uses-material-design: true

