name: drainit_petugas
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.1.0
  dcdg: ^4.0.1
  get: 4.6.3
  file_picker: ^4.5.1
  flutter_screenutil: ^5.4.0+1
  google_fonts: 2.1.1
  flutter_svg: 1.1.0
  persistent_bottom_nav_bar: 4.0.2
  line_icons: 2.0.1
  get_storage: 2.0.3
  geocoding: ^2.0.1
  google_maps_flutter: 2.1.1
  photo_view: ^0.13.0
  readmore: 2.1.0
  timeline_tile: 2.0.0
  flutter_native_splash: 2.2.2
  shimmer: 2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/png/
    - assets/svg/
  uses-material-design: true

